# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'weChatSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for weChatSwift

  pod 'GLTabBar', :git => "https://github.com/liujunliuhong/TabBar.git"


  target 'weChatSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'weChatSwiftUITests' do
    # Pods for testing
  end

end
